# Generated by Django 5.2.5 on 2025-11-07 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(choices=[('Automotive', 'Automotive'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Fashion - Men', 'Fashion - Men'), ('Fashion - Women', 'Fashion - Women'), ('Groceries & Gourmet', 'Groceries & Gourmet'), ('Health', 'Health'), ('Home & Kitchen', 'Home & Kitchen'), ('Pet Supplies', 'Pet Supplies'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Toys & Games', 'Toys & Games')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('employment_status', models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Student', 'Student'), ('Self-employed', 'Self-employed')], max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('education', models.CharField(choices=[('Secondary', 'Secondary'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], max_length=50)),
                ('household_size', models.IntegerField()),
                ('has_children', models.IntegerField()),
                ('monthly_income', models.FloatField()),
                ('preferred_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_email', models.CharField(max_length=50)),
                ('employee_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_customer', models.ForeignKey(default='x', on_delete=django.db.models.deletion.RESTRICT, related_name='customer_cart', to='onlineshopfront.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('Order Placed', 'Order Placed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], max_length=50)),
                ('order_date', models.DateField()),
                ('order_price', models.FloatField(default=0.0)),
                ('required_date', models.DateField()),
                ('shipped_date', models.DateField(blank=True, null=True)),
                ('shipping_fee', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer_orders', to='onlineshopfront.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('total_price', models.FloatField()),
                ('method', models.CharField(choices=[('Card', 'Card'), ('Paynow', 'Paynow'), ('Apple Pay', 'Apple Pay')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50)),
                ('transaction_ref', models.CharField(max_length=100, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='onlineshopfront.order')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='category_subcategory', to='onlineshopfront.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_category', models.CharField(choices=[('Automotive', 'Automotive'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Fashion - Men', 'Fashion - Men'), ('Fashion - Women', 'Fashion - Women'), ('Groceries & Gourmet', 'Groceries & Gourmet'), ('Health', 'Health'), ('Home & Kitchen', 'Home & Kitchen'), ('Pet Supplies', 'Pet Supplies'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Toys & Games', 'Toys & Games')], max_length=50)),
                ('quantity_on_hand', models.IntegerField()),
                ('reorder_quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('product_rating', models.FloatField()),
                ('product_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='onlineshopfront.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='onlineshopfront.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='onlineshopfront.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='onlineshopfront.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='onlineshopfront.product')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
