# Generated by Django 5.2.8 on 2025-11-09 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("onlineshopfront", "0003_customer_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="HiddenProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hidden_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_flag",
                        to="onlineshopfront.product",
                    ),
                ),
            ],
        ),
    ]
